import React from 'react';
import {ArrowRight,Building2,Compass,Leaf,ShieldCheck} from 'lucide-react';
export default function FragrancesPage(){
const items=[['Address','A good home starts with a good address. Understand connectivity, neighbourhood character and what surrounds the development.'],['Architecture','Proportion, daylight, circulation and material choices shape how a residence feels over time.'],['Landscape','Thoughtful green spaces create breathing room between buildings and bring nature into daily routines.'],['Amenities','The best amenities support the life you already have—wellness, family, recreation and social connection.']];
return <main className="bg-realestate-paper pb-24">
<section className="bg-[#2b2c27] py-20 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-[11px] uppercase tracking-[.18em] text-white/45">The experience</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold tracking-[-.05em] text-white sm:text-6xl">A considered approach to modern residential living.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/60">From the first visit to the details of everyday life, the experience is designed to feel clear, comfortable and distinctly human.</p></div></section>
<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10">
<div className="grid gap-px border border-realestate-line bg-realestate-line md:grid-cols-2">{items.map(([title,copy],i)=><div key={title} className="bg-realestate-paper p-8 sm:p-10"><p className="text-xs text-realestate-brass">0{i+1}</p><h2 className="mt-8 text-2xl font-semibold">{title}</h2><p className="mt-4 max-w-md text-sm leading-7">{copy}</p></div>)}</div>
<div className="mt-12 grid items-center gap-8 lg:grid-cols-[1fr_.8fr]"><div><p className="section-kicker">A calm visual language</p><h2 className="section-title mt-4 max-w-xl text-4xl sm:text-5xl">Less decoration. More intention.</h2><p className="mt-5 max-w-xl text-base leading-7">Materials, light and open space do the work. The result is a residential experience that feels refined without feeling staged.</p></div><div className="grid grid-cols-2 gap-3"><div className="border border-realestate-line bg-[#f2eee6] p-6"><Building2 className="h-5 w-5 text-realestate-brass"/><p className="mt-7 text-sm font-semibold">Built form</p></div><div className="border border-realestate-line bg-[#f2eee6] p-6"><Compass className="h-5 w-5 text-realestate-brass"/><p className="mt-7 text-sm font-semibold">Orientation</p></div><div className="border border-realestate-line bg-[#f2eee6] p-6"><Leaf className="h-5 w-5 text-realestate-brass"/><p className="mt-7 text-sm font-semibold">Landscape</p></div><div className="border border-realestate-line bg-[#f2eee6] p-6"><ShieldCheck className="h-5 w-5 text-realestate-brass"/><p className="mt-7 text-sm font-semibold">Clarity</p></div></div></div>
<div className="mt-14 border-t border-realestate-line pt-6"><a href="/contact" className="inline-flex items-center gap-2 text-sm font-semibold">Talk through a project<ArrowRight className="h-4 w-4"/></a></div>
</section></main>
}
