import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Mail,MapPin,Phone} from 'lucide-react';
export default function Footer(){return <footer className="bg-[#262723] text-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10">
<div className="grid gap-12 md:grid-cols-[1.3fr_.8fr_.8fr_1fr]">
<div><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center bg-white text-sm font-bold text-[#262723]">SP</div><div><p className="text-sm font-semibold text-white">Shapoorji Pallonji</p><p className="text-[10px] uppercase tracking-[.17em] text-white/45">Real Estate</p></div></div><p className="mt-6 max-w-md text-sm leading-7 text-white/58">A considered real-estate experience built around address, architecture, landscape and everyday living.</p></div>
<div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-white/35">Explore</p><div className="mt-4 space-y-3 text-sm text-white/70"><Link to="/" className="block hover:text-white">Home</Link><Link to="/products" className="block hover:text-white">Projects</Link><Link to="/about" className="block hover:text-white">Our Story</Link><Link to="/contact" className="block hover:text-white">Contact</Link></div></div>
<div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-white/35">Legal</p><div className="mt-4 space-y-3 text-sm text-white/70"><Link to="/privacy-policy" className="block hover:text-white">Privacy Policy</Link><Link to="/terms-and-conditions" className="block hover:text-white">Terms &amp; Conditions</Link><Link to="/disclaimer" className="block hover:text-white">Disclaimer</Link></div></div>
<div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-white/35">Visit / Contact</p><div className="mt-4 space-y-4 text-sm text-white/70"><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 text-[#b59767]"/><span>41/44, Shapoorji Pallonji Centre, Minoo Desai Marg, Colaba, Mumbai 400005</span></div><a href="tel:+918700983465" className="flex gap-3 hover:text-white"><Phone className="h-4 w-4 text-[#b59767]"/>+91 87009 83465</a><a href="mailto:viveklukar1999@gmail.com" className="flex gap-3 break-all hover:text-white"><Mail className="h-4 w-4 text-[#b59767]"/>viveklukar1999@gmail.com</a></div></div>
</div>
<div className="mt-12 flex flex-col gap-3 border-t border-white/10 pt-5 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p className="text-white/45">© 2026 Shapoorji Pallonji Real Estate. All rights reserved.</p><Link to="/contact" className="inline-flex items-center gap-2 hover:text-white">Speak to our team<ArrowUpRight className="h-3.5 w-3.5"/></Link></div>
</div></footer>}
